### ISSUE TITLE
The background color (green and blue) is not appearing on the conflicted code

### ISSUE THREAD

**Issue by ronakrrb** [smashwilson/merge-conflicts#100]
The merge conflict is not working properly i assume. Check the attached image

![screen shot 2015-01-15 at 3 04 25 pm](https://cloud.githubusercontent.com/assets/5681924/5755215/ff111d3c-9cc7-11e4-9298-51bfa9ca9673.png)

**Comment by smashwilson** [comment]
Ah, this is related to #99: merge-conflicts doesn't work with the shadow DOM, yet. I'm having a look presently. In the meantime, I'll close this as a duplicate :point_right:
