### ISSUE TITLE
Use of deprecated selectors

### ISSUE THREAD

**Issue by alex** [smashwilson/merge-conflicts#106]
With the latest atom I get warnings about deprecated selectors:

![screen shot 2015-01-17 at 1 00 10 pm](https://cloud.githubusercontent.com/assets/772/5789834/d817c302-9e48-11e4-8b38-0f636cfc11e3.png)

(Sorry I can't think of a better way to show this than a screenshot of the page)

**Comment by smashwilson** [comment]
Hey, @alex!

Yeah, there are currently a ton of deprecation warnings that I'm working through, little by little. I took care of the deprecated CSS selectors in 01b4fbc92, but there are a bunch of other problems related to basic functionality that make the last release nigh unusable on current Atom versions. `master` is *almost* working again, but it's still just broken enough that I don't want to push another one until I can get it limping the rest of the way.

If you're feeling adventurous and want to verify that I took care of all of these, you can run from master:

```
git clone https://github.com/smashwilson/merge-conflicts.git
cd merge-conflicts
apm install .
```

**Comment by smashwilson** [comment]
No more deprecated selectors in master. The next release will be clean:

![screen shot 2015-01-19 at 12 03 17 pm](https://cloud.githubusercontent.com/assets/17565/5804346/33bf7318-9fd3-11e4-8fa4-756a8943d5b6.png)

(It's hard to take a screenshot to show the *absence* of something, isn't it?)
