### ISSUE TITLE
Merge-Conflicts Highlighted Text

### ISSUE THREAD

**Issue by ahightman** [smashwilson/merge-conflicts#131]
After resolving merge-conflicts, staging commit, pushing, the conflicted text stays highlighted no matter what I do.

**Comment by smashwilson** [comment]
Oh hey, you're absolutely right. I usually close and re-open my open editors to clear them, but the *right* thing to do would be to clean up all of the live markers and decorations when the `didQuitConflictResolution` or `didCompleteConflictResolution` are emitted.

I'll have a look and see if I can get this working properly for 1.3.1.
