### ISSUE TITLE
Large merge conflict file list scrambles up screen

### ISSUE THREAD

**Issue by elexx** [smashwilson/merge-conflicts#138]
Having many files with merge conflicts results in a large merge-conflicts file list. In my case the file content area shrank down to a few lines. I also noticed that the merge conflict markers are drawn above of the file list (and above atoms tab bar).

A solution could be that the file list is re-sizable with its own scrollbar.

My Atom version is 0.190.0, merge-conflict version is 1.3.1, working on xubuntu 14.10.

![merge conflicts](https://cloud.githubusercontent.com/assets/221837/7133342/b90024b2-e292-11e4-88d8-99418f7a5f6c.png)

**Comment by smashwilson** [comment]
Oh wow, that's kind of nuts.

> A solution could be that the file list is re-sizable with its own scrollbar.

:+1: Seems reasonable to me.

> I also noticed that the merge conflict markers are drawn above of the file list (and above atoms tab bar).

That's... strange. The conflict markers are implemented as overlay decorations installed in the editor itself - I'm not doing my own rendering there. That might actually be an Atom bug, although I'd want to investigate before filing it as such.

**Comment by infinityCounter** [comment]
Bump :+1:
