### ISSUE TITLE
z-index issue with UI elements on horizontally split panes

### ISSUE THREAD

**Issue by itsjustmath** [smashwilson/merge-conflicts#145]
Both the buttons and the bright blue (HEAD) and green fields (commit number) have a z-index higher than any other element in the atom editor. This is happening when there are 2 panes stacked horizontally. The top file is a handlebars file and the bottom is a scss file.

![git_merge_z-index_bug](https://cloud.githubusercontent.com/assets/635044/7997015/d2950462-0adb-11e5-8f1d-e390038f9bd4.png)

**Comment by smashwilson** [comment]
Oh yeah, this is part of the problem in #138.

Thanks for the report :smile: I'll have a look the next day I'm hacking on this.

**Comment by itsjustmath** [comment]
Awesome. Thanks for the hard work!

**Comment by rmariuzzo** [comment]
@itsjustmath thanks for reporting this, I just noticed that same interface.

**Comment by zwacky** [comment]
+1

**Comment by smashwilson** [comment]
Hmm, this may have been fixed upstream:

![screen shot 2015-07-16 at 2 29 48 pm](https://cloud.githubusercontent.com/assets/17565/8731718/2cda6640-2bc7-11e5-9b71-eea7e5fd843d.png)

I tried to reproduce with a variety of themes and I couldn't. It may be a consequence of the editor tiling?

Can any of you still see this in a recent Atom? I'm on 1.0.2, for reference.

**Comment by smashwilson** [comment]
I'm going to close this for now. If any of you still see this happening, ping me here and be sure to let me know what UI and syntax themes you have active so I can try to reproduce it.
