### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by cyrilchapon** [smashwilson/merge-conflicts#147]
Opening a file with some 

```
<<<<<<< HEAD
blabla
=======
blibli
>>>>>>> blablacommit
```

and going *Packages/Merge Conflicts/Detect* doesn't do anything.

Is there any log or console or something I can paste here to help ?

**Comment by rgbkrk** [comment]
What does the developer console show (`Ctrl`+`Alt`+`I`)?

**Comment by cyrilchapon** [comment]
> What does the developer console show (Ctrl+Alt+I)?

An error

```
"Error: abnormal git exit: 128
'\\dev\cch\www\rfidlocator-api'
CMD.EXE a �t� d�marr� avec le chemin d'acc�s comme r�pertoire en
cours. Les chemins d'acc�s UNC ne sont pas prise en charge. Utilisation
du r�pertoire Windows par d�faut.

fatal: Not a git repository (or any of the parent directories): .git

    at exitHandler (C:\Users\Cyril\.atom\packages\merge-conflicts\lib\git-bridge.coffee:123:26)
    at triggerExitCallback (C:\Users\Cyril\AppData\Local\atom\app-0.209.0\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\Cyril\AppData\Local\atom\app-0.209.0\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (child_process.js:1057:12)"
```

I guess this is because my project is located on a remote linux machine `\\dev` that I access over SAMBA, isn't it ?

**Comment by smashwilson** [comment]
> I guess this is because my project is located on a remote linux machine \\dev that I access over SAMBA, isn't it ?

That seems likely!

Can you run things like `git status` from the command-line in that directory okay?

**Comment by cyrilchapon** [comment]
> Can you run things like git status from the command-line in that directory okay?

Nope. I use git from an ssh in the same directory.

**Comment by smashwilson** [comment]
Ah. I'm afraid there's not much merge-conflicts can do for you, then - it shells out to git to enumerate conflicts, mark conflicts as resolved, and a few other key things.

Do the other git-centric features of Atom work as expected? (Gutter decorations for changes, the current branch and ahead/behind display in the status bar, and so on.) If so, #12 might be what you need.

**Comment by cyrilchapon** [comment]
Thining of this, it makes sense. The plugins just use git commands doesn't it ? This should be closed

> Do the other git-centric features of Atom work as expected?

It depend on many things, including repo config and carrier returns.

**Comment by smashwilson** [comment]
> The plugins just use git commands doesn't it ? This should be closed

Yah, I suppose so. :bow:

Thanks for the report just the same!
