### ISSUE TITLE
No conflicts detected, although there are.

### ISSUE THREAD

**Issue by tdbs** [smashwilson/merge-conflicts#150]
The files in question are python files.
What else can i say to help?
I am on OSX, if its relevant

**Comment by rgbkrk** [comment]
Maybe paste what the conflicts look like along with any output in the Developer console?

**Comment by smashwilson** [comment]
Just a wild guess - do you have multiple Project Folders open in the left panel?

**Comment by tdbs** [comment]
i might have had multiple folders open, is this an issue?

**Comment by smashwilson** [comment]
Oh! Sadly, yes. When support for multiple projects shipped, I didn't devote the time to handle it properly. There's a lot of `atom.projects.getRepositories()[0]` going on.

I'm tracking this one in #91 if you want to subscribe over there.

Can you attempt to reproduce with a single project open, and close the issue if you can't?

**Comment by tdbs** [comment]
Ok, thank you for your input, next time i have a conflict i'll try to sort this out, and close the issue if i can

**Comment by rmariuzzo** [comment]
Thanks @smashwilson for the input and the honesty.
