### ISSUE TITLE
nothing happening on Mac

### ISSUE THREAD

**Issue by SirZach** [smashwilson/merge-conflicts#166]
I tried doing <code>alt+m down</code> and other variations and I can't get that conflicts file to show up. The console didn't yield any errors or warnings.

![screen shot 2015-07-17 at 1 58 49 pm](https://cloud.githubusercontent.com/assets/1113484/8753737/0af08eb8-2c8c-11e5-9768-65d23b9c8390.png)

Atom version 1.0.2.
merge-conflicts version 1.3.3

**Comment by smashwilson** [comment]
It's `alt-m d` to detect conflicts. You can also run "Merge Conflicts: Detect" from the command palette, or check the keybinding resolver to see if something is conflicting - I just shuffled them from `ctrl-m` chords in #157 because *those* conflicted.

**Comment by SirZach** [comment]
got it. i'll close for now. i didn't realize i had to run a command although i'm pretty sure i tried alt+m d. thanks for the response!
