### ISSUE TITLE
Update 1.3.5 is broken? 

### ISSUE THREAD

**Issue by gustaflindqvist** [smashwilson/merge-conflicts#174]
The update from 1.3.4 to 1.3.5 is not working for in Atom.app on Mac OS X. Atom is trying to update but it's just loading.

If I uninstall the plugin and reinstall the current version is 1.3.4.

**Comment by smashwilson** [comment]
Well that's no good.

Can you update from the command line?

```bash
apm install merge-conflicts
```

**Comment by gustaflindqvist** [comment]
I was able to use:

```apm update merge-conflicts```

Then Atom updated the packages to 1.3.5. :+1:

**Comment by smashwilson** [comment]
This one was related to settings-view/apm bug, which I've seen sporadically myself. Thanks for the report!
