### ISSUE TITLE
HowTo Guide

### ISSUE THREAD

**Issue by raeffu** [smashwilson/merge-conflicts#176]
The ReadMe doesn't really cover how to **use** merge-conflicts. Me for example, I don't get how to use both versions of a conflict.

So a HowTo guide or a better README would be nice!

**Comment by j2emanue** [comment]
i cant figure out how to use it either.

**Comment by smashwilson** [comment]
You know, you're absolutely right! I gave it a shot in #178.

> Me for example, I don't get how to use both versions of a conflict.

To answer your specific question: if you right-click within an active conflict chunk, you'll see "Resolve" options in the context menu:

![screen shot 2015-08-20 at 9 39 03 am](https://cloud.githubusercontent.com/assets/17565/9384563/4ee9ed1e-471f-11e5-9cb3-b3a4ccb46506.jpeg)

("Current" is the one your cursor is in, which is more useful if you're using it with a hotkey.) Of course, you can also do it by hand, by copying and pasting one side at the end of the other.

**Comment by smashwilson** [comment]
I'll close this for now, since we have *some* kind of usage section there, now. Let me know if there's anything I didn't cover.

**Comment by raeffu** [comment]
@smashwilson great thx for your work! :+1: It's now easier to understand. I'm missing only a short explanation what the resolve options are. For example it isn't obvious what "ours then theirs" does.
