### ISSUE TITLE
How Do I Personalize the keybinding?

### ISSUE THREAD

**Issue by eltommy99** [smashwilson/merge-conflicts#214]
is its possible to personalize them? If it´s not, then why cant i get it to open with the keybindings it says...

**Comment by smashwilson** [comment]
It is indeed possible to personalize! Choose "Keymap..." from your Atom menu and add CSON to set the keybindings to whatever you wish. You can copy and paste this and change the keys to whatever you prefer:

```cson
'atom-text-editor.conflicted':
  'alt-m down': 'merge-conflicts:next-unresolved'
  'alt-m up': 'merge-conflicts:previous-unresolved'
  'alt-m enter': 'merge-conflicts:accept-current'
  'alt-m r': 'merge-conflicts:revert-current'
  'alt-m 1': 'merge-conflicts:accept-ours'
  'alt-m 2': 'merge-conflicts:accept-theirs'

'atom-workspace':
  'alt-m d': 'merge-conflicts:detect'
```

The Atom docs have [basic](https://atom.io/docs/v1.6.0/using-atom-basic-customization#customizing-key-bindings) and [advanced](https://atom.io/docs/v1.6.0/behind-atom-keymaps-in-depth) guidelines describing the syntax.

If it won't open for you, you may have conflicting keybindings from another package. Check the "Keybindings" tab in your Settings page and explore with the keybindings resolver (run `Key Binding Resolver: Toggle` from the command palette or use the hotkey to launch it, `⌘ .` on a Mac).

**Comment by smashwilson** [comment]
I'm adding a section on this to the README in #230. :sparkles:
