### ISSUE TITLE
Finds conflicted files but no visual feedback

### ISSUE THREAD

**Issue by stephenbe** [smashwilson/merge-conflicts#223]
As you can see it detect the files that are in conflict, but I don't have any of the visuals that help with the conflict

![2016-04-13_10-33-43](https://cloud.githubusercontent.com/assets/3018441/14497003/493a3ff0-0163-11e6-8857-0766941f650a.png)

**Comment by saidmoya12** [comment]
Same issue with the last update

**Comment by bfrazier2** [comment]
Same issue

**Comment by smashwilson** [comment]
I'm closing this as a duplicate of #227. Please subscribe over there for updates :bow:
