### ISSUE TITLE
Marks wrong lines on diff3 without base content

### ISSUE THREAD

**Issue by ypresto** [smashwilson/merge-conflicts#225]
```
<<<<<<< Updated upstream
    private static final int INDICATOR_ANIMATION_DURATION_MILLIS = 150;
||||||| merged common ancestors
=======
    private static final int MAX_SCROLL_DISTANCE = 6;
>>>>>>> Stashed changes
```

will cause bug...

![image](https://cloud.githubusercontent.com/assets/400558/14555957/9676d5a2-0330-11e6-902e-7db140744953.png)

**Comment by smashwilson** [comment]
Just verified that this works properly in 1.4.2:

![screen shot 2016-04-25 at 3 02 59 pm](https://cloud.githubusercontent.com/assets/17565/14795511/d225d526-0af6-11e6-8892-6c62ea5efa77.jpeg)

**Comment by ypresto** [comment]
Thanks..!!!
