### ISSUE TITLE
Conflict detection doesn't work if no conflict in the first project folder on 1.4.x

### ISSUE THREAD

**Issue by emileber** [smashwilson/merge-conflicts#228]
it doesn't work if there are no conflicts in the first project folder.

I get the following notification (on version 1.4.1):

> Nothing to Merge
> No conflicts here!

I played around swapping the order of the project folder and it works only if the conflicts are on the first project folder.

I reverted to 1.3.7 and it detects the conflicts if I open a file of the project. So the problem exist only in 1.4.x

**Comment by smashwilson** [comment]
:wave: Thanks for taking the time to file an issue here! Unfortunately, this repository is being [deprecated](https://github.com/smashwilson/merge-conflicts/blob/master/docs/announcement.md), so I won't be getting to this one here.

This one should be taken care of by the [new git and GitHub package for Atom](https://github.com/atom/github) where we have a bunch of logic to follow the "active" project (use a single project if there's only one, follow the active pane, etc). If you see something similar, please [file an issue there](https://github.com/atom/github/issues/new) to let us know. Thanks 🙇

**Comment by emileber** [comment]
It's cool, thanks for taking the time to inform me. I didn't really needed to use multiple projects per atom instance and instead used multiple atom instance, one for each project.
