### ISSUE TITLE
Keep both?

### ISSUE THREAD

**Issue by jglovier** [smashwilson/merge-conflicts#244]
Is there a good way to keep both? Right now you are sort of forced to choose between options. There are some instances where I need to just keep both, and I've had to resort to copying one of the lines, accepting one of the diffs, then pasting back in the code.

Maybe with an button like `Keep both` it could just remove the conflict marking lines and keep everything else as is?

**Comment by smashwilson** [comment]
You actually already can! It's kind of hidden, though. Right-click within a conflict marker and you'll see a `Resolution` submenu that lets you choose "ours then theirs," "theirs then ours," and so on.

**Comment by jglovier** [comment]
Ah, awesome!

What do you think about making that more obvious with a little menu icon or something?

**Comment by smashwilson** [comment]
I like the idea - I was thinking about adding a cog menu to the navigator (the bar between the sides of the diff) for example.

Unfortunately me spending time on this package these days is... sporadic and burst-y at best. 😛 

Oh, also, see the existing discussion in #185. Mind if I close this issue as a duplicate of that one?

**Comment by jglovier** [comment]
Sounds good. 👍
