### ISSUE TITLE
Theme with large buttons hides conflict's first line

### ISSUE THREAD

**Issue by mateosss** [smashwilson/merge-conflicts#250]
I'm using atom-material-ui theme and it has large buttons, merge-conflicts uses this buttons for showing up the 'use me' buttons, the problem (as showed in the picture below) is that first line after 'our changes' section gets semi-covered, as equal as the first line after the conflict, this image is zoomed in, with normal zoom the lines appear full-covered as if there weren't there.

Can this be fixed from this package or should I request atom-material-ui to get their buttons smaller (which probably they won't do)?

![captura de pantalla de 2016-09-19 21-56-12](https://cloud.githubusercontent.com/assets/5622899/18654059/9a9df1ce-7eb4-11e6-8819-6e6c84c7eace.png)

Thanks for the great package!

**Comment by burkhardr** [comment]
@smashwilson Same issue here. Could these be text links instead?

**Comment by pingshunhuangalex** [comment]
+1, same issue here for material-ui theme (dark).

**Comment by tsuyaochang** [comment]
+1, same issue here.
atom 1.12.5
material-ui  (dark)
base16 tomorrow dark
mac os

**Comment by ClydeDroid** [comment]
+1 same issue
atom 1.12.6
atom-material-ui theme
one dark syntax
ubuntu 16.04

**Comment by smashwilson** [comment]
:wave: Thanks for taking the time to file an issue here! Unfortunately, this repository is being [deprecated](https://github.com/smashwilson/merge-conflicts/blob/master/docs/announcement.md), so I won't be getting to this one here.

This one should be taken care of by the [new git and GitHub package for Atom](https://github.com/atom/github) - the conflict controls are block decorations, so they should resize to fit the buttons. If you still see something similar, please [file an issue there](https://github.com/atom/github/issues/new) to let us know. Thanks 🙇

**Comment by mateosss** [comment]
Thanks for your work in this package! it was very useful, and indeed they solved this issue, so I suppose I should close this.
