### ISSUE TITLE
Nothing to merge issue

### ISSUE THREAD

**Issue by bjankord** [smashwilson/merge-conflicts#50]
I'm having trouble getting this plugin to work. 

In terminal from my gh-pages branch I ran `git merge 0.3.0` to merge a v0.3.0 branch into my gh-pages branch. 

Got some merge conflicts in the process. Ran `atom .` to open the project in the editor and then typed `cmd+alt+m` and see a pop-up:

Nothing to Merge. No conflicts here!

I'm seeing markers in the code:

```
<<<<<<< HEAD
some code
=======
some different code
>>>>>>> 0.3.0
```

Maybe I'm missing a step? I was expecting to get the badass merge conflict UI and start flying through fixing merge conflicts.

**Comment by btm1** [comment]
I'm also having this issue mine are all modified:

        'Unmerged paths:
        (use "git add <file>..." to mark resolution)

	both modified:   web-app/css/bf.css
	both modified:   web-app/js/controllers/revWaterfallCtrl.js
	both modified:   web-app/less/styles.less'

But it tells me there is nothing to merge
