### ISSUE TITLE
The merge conflict package works not always.

### ISSUE THREAD

**Issue by ronakrrb** [smashwilson/merge-conflicts#81]
@smashwilson Some times, it show me the USE ME button, whereas some times i have to make a change and then undo to get the USE ME button. In the second case, the percentage bar showing the progress at the bottom doesn't update

**Comment by smashwilson** [comment]
I've touched up a fair number of other bugs since you've submitted this. Are you still seeing this on 1.3.1? If so, any stack traces showing up in your console?

**Comment by ronakrrb** [comment]
Hey,

Thanks for the update. I haven’t come across any merge conflict but will surely reply back if the issue still exists with stack traces.

Best wishes,
Ronak Bhandari
Data Artist, pykih.com <http://pykih.com/> | +91-99309-90332
Need beautiful Javascript Charts? Use our open source library http://pykcharts.com <http://pykcharts.com/>

**Comment by smashwilson** [comment]
I'll close this for now because I've changed a ton since this came up. Let me know if it's still a problem on a recent Atom and merge-conflicts :smile:
