### ISSUE TITLE
Use event-kit instead of emissary

### ISSUE THREAD

**Issue by smashwilson** [smashwilson/merge-conflicts#86]
To stay up to date with the rest of Atom.

**Comment by smashwilson** [comment]
Actually, `Emitter` is now [bundled with Atom](https://atom.io/docs/latest/upgrading/upgrading-your-package#eventing-and-disposables).

**Comment by smashwilson** [comment]
Done with #104. :sparkles:

I still don't think I'm disposing of subscriptions everywhere I should be, though.

**Comment by rgbkrk** [comment]
Does this mean I have to update atom achievements?
