### ISSUE TITLE
Support three-way merge markers

### ISSUE THREAD

**Issue by smashwilson** [smashwilson/merge-conflicts#9]
You can configure `git` to show the common ancestor in merge conflicts as well with:

```bash
git config --global merge.conflictstyle diff3
```

I'd like to support this by adding another `SideView`, and possibly adding a package setting that's synchronized to your global `.gitconfig`.

**Comment by malexandre** [comment]
I love this plugin, but I need the three way merge to work. On a real bad conflict, I can't get my head around it without it. Can't wait to see this done!

**Comment by ypresto** [comment]
+1

**Comment by rjmunro** [comment]
+1

**Comment by dkarter** [comment]
+1 can't live without the three way merge on those complex merges

**Comment by rbrochot** [comment]
+1 
I can't understand why this setting isn't more widely used/supported.

**Comment by mbidewell** [comment]
Adding this would be awesome!

**Comment by mokkabonna** [comment]
+1

**Comment by dorian-marchal** [comment]
:+1:

**Comment by ryanhiebert** [comment]
:+1:
