### ISSUE TITLE
Handle multiple git repositories and multiple directories per project

### ISSUE THREAD

**Issue by smashwilson** [smashwilson/merge-conflicts#91]
`atom.project` now has plural *getRepositories()*, *getDirectories()*, and *getPaths()* methods, to anticipate multi-directory projects. Currently I'm just yanking the first of each as a stopgap, but I'd like to add proper support for all of these.

**Comment by auxiliary** [comment]
Maybe you can use 
```
editor = atom.workspace.getActivePaneItem()
file = editor?.buffer.file
``` 
to get the current selected file and choose the repo that contains it using `atom.project.contains()`. 
I am not very familiar with Coffeescript to make the changes.
