### ISSUE TITLE
Change click to dismiss to auto-dismiss timeout

### ISSUE THREAD

**Issue by ilanbiala** [smashwilson/merge-conflicts#94]
Click to dismiss disrupts the workflow, not really a good idea. I would just setTimeout on a div then kill the Div after 5s or whatever.

**Comment by ilanbiala** [comment]
@smashwilson can you think of anyone who would use Git from within a text editor and not be familiar with it?

**Comment by rgbkrk** [comment]
@ilanbiala Maybe submit a PR that provides it as an option? The default should be click-to-dismiss in my opinion for the sake of newcomers. Advanced users can be forced to set a configuration option.

It's hard to estimate the user base at large and my own experience differs, but I've recommended Atom as a good starting editor for large swaths of new comers in workshops and teaching environments. Some of these folks (largely Windows users) are used to a click-flow and Windows is still the dominant desktop.

**Comment by EthanML** [comment]
I agree, I'd like to see keyboard shortcuts to access 'stage', 'mark as resolved', etc. - or at the very least a button to dismiss the window as @smashwilson mentioned above. Anything to avoid taking my hands off the keyboard all the time.

**Comment by smashwilson** [comment]
As an update: there is an [experimental API for notifications](https://github.com/atom/atom/blob/master/src/notification.coffee) in Atom that I've been keeping an eye on. I'd much rather use the built-in support than the half-baked thing I rolled up for this, but I'd rather not port everything over until it's stable.

If *those* don't have some kind of keyboard shortcut support, I'll PR that upstream to Atom :wink:

> @smashwilson can you think of anyone who would use Git from within a text editor and not be familiar with it?

I have taught git to a large number of developers, from novice to veteran, some subset of whom were using Atom, so... yes, I personally know many such people! I've even helped set up an event that introduced high school students to programming -- the first code these students have ever touched -- and *they* were using Atom. It's actually quite accessible as a first editor, and its audience is much larger than "experienced GitHubbers."
