### ISSUE TITLE
Git add failed: exit code 128. index.lock exists

### ISSUE THREAD

**Issue by mikeraimondi** [smashwilson/merge-conflicts#96]
When I try to stage a file through the UI, I see the following error:

```
Error: git add failed: exit code 128

fatal: Unable to create '/path/to/my/project/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
```

The issue is that there is no such file in `.git/`.

Speculation: some other process in Atom is calling Git commands and causing the utility to lock.

**Comment by smashwilson** [comment]
I was able to replicate this almost every time when you first posted this, but now I can't replicate it at all. My guess is that there was an Atom git-utils call that wasn't cleaning itself up properly before, but now it is.

I'll leave this open - let me know if you're still able to replicate once 1.2.9 is out.

**Comment by smashwilson** [comment]
I've definitely seen this a ton, now. It doesn't happen *every* time but it's pretty frequent - at least on the Mac. That smells like a timing bug to me.

Maybe it would help to use the [git-utils](https://github.com/atom/git-utils#repositoryaddpath) call to stage the file, rather than shelling out?

**Comment by smashwilson** [comment]
And now I haven't seen this for a long time. I'm guessing it was an upstream problem that's since been corrected.
