### ISSUE TITLE
Broken with Atom's new shadow DOM

### ISSUE THREAD

**Issue by danielmahon** [smashwilson/merge-conflicts#99]
Git merge "changes" do not appear when the Shadow DOM is enabled in Atom.io settings. Only the headings "//our changes, //their changes" are visible.

**Comment by smashwilson** [comment]
Er, this is now [rather more urgent](http://blog.atom.io/2015/01/05/enable-shadow-dom.html). Fortunately I believe #93 *might* address this, but I'll need to test. I should have time in a day or so.

**Comment by smashwilson** [comment]
Well well. #93 ended up being more work than I was hoping it would be. Let's see if I can fix just the shadow DOM bits, instead, to unbreak things quickly.

**Comment by smashwilson** [comment]
Back in business!

![screen shot 2015-01-19 at 10 57 14 am](https://cloud.githubusercontent.com/assets/17565/5803166/f726c8f6-9fc9-11e4-8f00-f648a16e928c.png)

 Still a few visual issues, but we're up and running again. The next release should be operable again.

**Comment by danielmahon** [comment]
thanks!
